### ISSUE TITLE
模型中间层问题

### ISSUE THREAD

**Issue by m2023hi** [dylan1034/FluidNet#4]
请教一个问题，为什么训练的时候不需要考虑 pos = vel * data[5][0] + data[0][0][:, :3]更新位置？
           不考虑的话模型预测往后时间帧的位置的能力会不会没有学习到？
           [pred] = model.train(sess, data, onlypred=True)
            vel = pred[0]
            pos = vel * data[5][0] + data[0][0][:, :3]

**Comment by dfldylan** [comment]
yes, in this code we just show how our network does work. For the pred pipeline, it's easy to write and varied from need.
